### ISSUE TITLE
Issue with new v1.6.1-1 prerelease

### ISSUE THREAD

**Issue by xor-gate** [xor-gate/syncthing-macosx#111]
Hi @calmh I have an issue with the new prerelease build from v1.4.2-1 git commit hash 3463cb3 located in TeamCity [here](https://build.syncthing.net/viewLog.html?buildId=61443&buildTypeId=SyncthingMacOS_BuildReleaseDmg).

<img width="488" alt="Screenshot 2020-04-17 at 14 58 12" src="https://user-images.githubusercontent.com/1050166/79571803-199abe00-80bc-11ea-93d7-385e821a198d.png">

Is there something wrong with the developer key?

**Comment by xor-gate** [comment]
I tried to reinstall the old https://github.com/syncthing/syncthing-macos/releases/tag/v1.0.0-2 release and it works fine without this error.

**Comment by imsodin** [comment]
Apple made notarization mandatory since the last release and a quick search/look didn't turn anything up that looks like doing notarization in syncthing-macos (aka searching for `notari` doesn't give results :) ). See https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by calmh** [comment]
It's a conundrum. Like many things in the Apple build ecosystem it's not trivial to automate. I have a script I run manually (when I remember, which I didn't for 1.4.2) to notarize the regular Syncthing binary after we release it.

**Comment by calmh** [comment]
And even then there's nonsense like this

```
2020-04-17 15:26:13.902 altool[34909:6901889] *** Error: Unable to notarize app.
2020-04-17 15:26:13.902 altool[34909:6901889] *** Error: code 1048 (You must first sign the relevant contracts online. (1048))
```

every time, even though I just signed the new contracts, and there are new contracts every few weeks 😬

**Comment by xor-gate** [comment]
Oohw boy, you dance with the devil.

**Comment by calmh** [comment]
Oh, the best thing is that when the notarization upload actually *works*, the tool just thanks you for the upload. Then at some later point you get the success/failure of the notarization process *in an email*. Excellent for integrating into a build pipeline.

**Comment by calmh** [comment]
Then you get an email like this, and have to run another tool with the guid to get the reason why it failed, which will likely be something meaningless as well

<img width="627" alt="Screen Shot 2020-04-17 at 15 35 53" src="https://user-images.githubusercontent.com/125426/79574909-338acf80-80c1-11ea-99d8-87add6855d79.png">

**Comment by calmh** [comment]
In this case, specifically, 

```
          Date: 2020-04-17 13:33:38 +0000
          Hash: 5b2d743dcbc09044d95ef4eccb182bc11f95efdd03bbbf01b68ea77f585bdcbf
    LogFileURL: https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/81/cb/1a/81cb1adf-29b1-af25-a596-c11816113ee4/developer_log.json?accessKey=1587325082_3954166839147991973_ctuoSbs4eJk2rq3BpULmpRVC3auTPTy3VLy3fyrfRINDOb8lbTZbiDPZrVZuwV%2FncJK3k2GtiPa%2BVi8bzd73VUXjVZBERZ6z7iDFNt5g9qhwv4O2B8fRCU0nYkfM9s0FUB320LIO3QDVkZb5dsOQacYoZlb8ipoZSYs6SzlDgEA%3D
   RequestUUID: 3af12861-9645-4a41-b385-d3bbc642b15c
        Status: invalid
   Status Code: 2
Status Message: Package Invalid
```

Ah. "Package Invalid". I see. 😠

**Comment by calmh** [comment]
```
"message": "The executable does not have the hardened runtime enabled.",
```

I think that means we need a newer Go (1.14). Whether you then also need to do some magic here I don’t know.

**Comment by xor-gate** [comment]
Can we try to compile 1.5.0 syncthing with a correctly signed cert and see if we can get it working? When the release is ready of course.

**Comment by xor-gate** [comment]
Now v1.5.0 is released can you have a look to upgrade to go 1.14 for macOS ? I still get the same error but then with the latest v1.5.0 so i'm unable to resolve #113.

**Comment by calmh** [comment]
Go 1.14 didn't change this situation, at least not by itself. I'm upgrading the builder to catalina and newer xcode to see what happens.

**Comment by imsodin** [comment]
Go itself should be "compatible" since 1.13.5: https://github.com/golang/go/issues/35748

**Comment by calmh** [comment]
Yeah so we're hitting something else then, maybe our linker flags or some other oddness.

```
"issues": [
    {
      "severity": "error",
      "code": null,
      "path": "syncthing-macos-amd64-v1.6.0-rc.1.zip/syncthing-macos-amd64-v1.6.0-rc.1/syncthing",
      "message": "The executable does not have the hardened runtime enabled.",
      "docUrl": null,
      "architecture": "x86_64"
    }
  ]
```

(Go 1.14.2)

**Comment by calmh** [comment]
Figured it out, it needs to be enabled at code signing time as well. So 1.6.0-rc.1 and newer will be notarized.

**Comment by calmh** [comment]
So Syncthing itself is now notarized, so I expect this is fine? It should be possible to do a release with an updated binary?

**Comment by calmh** [comment]
I fixed the DMG build for Catalina, but the app doesn't notarize very well regardless: https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/29/34/a5/2934a52d-e1f1-8589-b460-ae93de075f9c/developer_log.json?accessKey=1591361341_1785601510916194979_dQSsDjOSH3ciNP%2BFdg0CJ0CtJeH2LB3X%2FXw9lG8Lwf7oNf23xxRojOqSjLbfmf%2F7nxKY9Vsdc8f4SJGKGsohiW1uRr70XHMSsCWXpz2NsbiSFwtySSG6150LjQPNy8vI8MJY55Utm%2FTAJZR2K%2FoLemD8WlPkqWDIxxv8m4YG9k0%3D

Many things are unsigned or not hardened, which I guess is a question of enabling the appropriate things in the project? (Ignoring the syncthing binary itself since that build still points at 1.5.0.)

**Comment by xor-gate** [comment]
I have created a PR to update to 1.6.1 but still the same problem. The build is located here: 
https://build.syncthing.net/viewLog.html?buildTypeId=SyncthingMacOS_BuildReleaseDmg&buildId=67429&branch_SyncthingMacOS=release%2F1.6.1-1

**Comment by calmh** [comment]
What is "the same problem" exactly?

**Comment by calmh** [comment]
Syncthing itself is signed, hardened and notarized. However the other binaries in the package lack  signing or hardening: [notarization log for the 1.6.1-1 build](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/54/67/33/5467334c-d471-ce1a-51db-301bb9ec75ee/developer_log.json?accessKey=1591384146_1547560233062611337_TYI%2B8Va%2BkCEtnyL1WkMI%2F7YiYbpeF0DLrTH9wMNHABOkjNcTNdREPHCnNa9%2Fe0rZSZcWNsqEhRTQzKh43L06N6cYk6JZtYcf6ax8Mp1CBnt4omq38hAwPVZusiGUbGA7KcGkN32GApTKZPaHYdEkIgfdBYmweBZ%2Bxrt2eGutR3w%3D)

**Comment by xor-gate** [comment]
Application doesn't start, same as before:
![](https://user-images.githubusercontent.com/1050166/79571803-199abe00-80bc-11ea-93d7-385e821a198d.png)

**Comment by calmh** [comment]
Right, because it's not notarized, because see above.

**Comment by xor-gate** [comment]
I think we are hitting two related issues:
- https://github.com/sindresorhus/LaunchAtLogin/issues/20
- https://github.com/sparkle-project/Sparkle/issues/1266
It seems for most people the codesign --deep solves te problem

**Comment by xor-gate** [comment]
Seems we already do deep codesign, but the hardened is not enabled for sparkle probably. No direct clue how to enable it.

https://github.com/syncthing/syncthing-macos/blob/c52d8d67ba5003558d50718ed5c26a972b87b1f9/syncthing/Scripts/create-dmg.sh#L42

**Comment by xor-gate** [comment]
Seems there are some problems with the dmg:
- Download latest release from teamcity
- Install to Downloads folder
- Run `codesign -vvv --deep --strict ~/Downloads/syncthing.app`
```
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCore.dylib
/Users/jerry/Downloads/syncthing.app: resource fork, Finder information, or similar detritus not allowed
In subcomponent: /Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCore.dylib
```
- Executing `xattr -cr ~/Downloads/Syncthing.app` 
- Then the application can be opened
- Run codesign check again
```
codesign -vvv --deep --strict ~/Downloads/syncthing.app
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCoreGraphics.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftObjectiveC.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftObjectiveC.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCore.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCore.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftCoreFoundation.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftDispatch.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftDispatch.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftIOKit.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftIOKit.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftDarwin.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftDarwin.dylib
--prepared:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftFoundation.dylib
--validated:/Users/jerry/Downloads/Syncthing.app/Contents/Frameworks/libswiftFoundation.dylib
/Users/jerry/Downloads/syncthing.app: valid on disk
/Users/jerry/Downloads/syncthing.app: satisfies its Designated Requirement
```

**Comment by xor-gate** [comment]
Apple has the error documented: https://developer.apple.com/library/archive/qa/qa1940/_index.html

**Comment by xor-gate** [comment]
Seems the dmg app bundle is correct after some investigation. Only when copy it gets the quarantine attribute:

```
xattr -lr /Applications/Syncthing.app
/Applications/Syncthing.app: com.apple.quarantine: 0181;5ed7b971;Chrome;52919DD0-D83C-4501-A154-2CFBED6A439A
```

**Comment by calmh** [comment]
[Just the sparkle stuff left](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/f4/20/39/f4203959-082c-10e5-11d8-60a0002897b2/developer_log.json?accessKey=1591391748_8912819590617621253_odURzGerhif0W75aPsDWFovTDR%2BYkOaTj2vn03%2BUxXcxr%2Fi0qUP6eCTiRY0AnvtlLmUatc8e31zWiDVGkN%2BezgK%2BRAVzXlLdLxVr2TLKkLoLT2fGITU8%2FMev4lmOrFsaoRoeCu%2BebhcJC0FVeaPbk0SGFTLsq6HC%2FflsqGMX9YY%3D)

**Comment by xor-gate** [comment]
- I have added codesign for the sparkle stuff according to https://github.com/sparkle-project/Sparkle/issues/1389#issuecomment-507950890
- Try notarize artifact https://build.syncthing.net/viewLog.html?buildId=67486&buildTypeId=SyncthingMacOS_BuildReleaseDmg&tab=artifacts

**Comment by calmh** [comment]
<img width="571" alt="Screen Shot 2020-06-03 at 17 37 35" src="https://user-images.githubusercontent.com/125426/83657279-ef945100-a5c0-11ea-9c70-813efa68954b.png">

**Comment by xor-gate** [comment]
It works!

**Comment by xor-gate** [comment]
@calmh I found a nice tool to check if an app is correct:
https://eclecticlight.co/2019/05/31/can-you-tell-whether-code-has-been-notarized/
https://eclecticlight.co/taccy-signet-precize-alifix-utiutility-alisma/
<img width="592" alt="Screenshot 2020-07-10 at 15 52 36" src="https://user-images.githubusercontent.com/1050166/87161861-63630100-c2c5-11ea-939f-28c7a963b616.png">
